CREATE TABLE etage (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(255), numero INTEGER NOT NULL, superficie INTEGER NOT NULL);

CREATE TABLE salle (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(255), id_etage INTEGER NOT NULL, capacite INTEGER NOT NULL);